name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Install Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 22.21.0
          cache: "yarn"

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-scripts

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

  build:
    needs: quality
    uses: ./.github/workflows/reusable-build.yml
    with:
      flavor: ci
    secrets: inherit
