name: Lint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    timeout-minutes: 25

    steps:
      - name: Check out Git repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Install Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 22.21.0

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-scripts

      - name: Validate current commit (last commit) with commitlint
        run: npx commitlint --last --verbose

      - name: Test
        run: yarn test

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Format check
        run: yarn format-check
